<div class="items">
    <div class="wrapper clearfix">
        <div>
        <?php
            echo $this->tag->linkTo(array('http://booking.com'.$item->getUrlOrig(), $item->getName(),
                'local' =>FALSE,
                'target'=>'_blank'
            ));
        ?>
        </div>
        <div class="small"><?= $item->cities->getTitleRu().', orig. '.$item->getAddress() ?></div>
    </div>
</div>