<div class="items">
    <div class="wrapper clearfix">
        <div>
        <?php
            echo $this->tag->linkTo(array('http://booking.com'.$item->hotels->getUrlOrig(), $item->hotels->getName(),
                'local' =>FALSE,
                'target'=>'_blank'
            ));
        ?>
        </div>
        <div class="small"><?= $item->city_name.', '.$item->region_name ?></div>
    </div>
</div>