<div class="content">
    <div class="content-wrapper">
        <div class="hotels-grid clearfix">
            <div class="city-selector">
                <?= $this->tag->form(array('hotels/', 'method'=>'get')) ?>

                <?=
                $this->tag->select(array('city', $cities,
                    "using" => array("city_id", "title_ru"),
                    "useEmpty" => true,
                    'emptyText' => 'выберите город...',
                    'emptyValue' => '0',
                    'onchange'=>'this.form.submit();',
                )) ?>

                <?= $this->tag->endForm(); ?>
            </div>

            <div class="small total">Всего: <b><?= $this->tag->linkTo('hotels'.(($city = $this->request->get('city')) ? '/?city='.$city : ''), $grid->total_items) ?></b></div>

            <?php
            if(!empty($grid)){
                foreach($grid->items as $item){
                    $this->partial('hotels/gridItem');
                }
            }
            ?>
            </div>

            <?= $this->partial('paginator') ?>
    </div>
</div>