<!DOCTYPE html>
<html>
<head>
	<?= $this->tag->getTitle() ?>
	<?= $this->tag->tagHtml('meta', array('name'=>'description', 'content'=>(!empty($metaTags['description']) ? $metaTags['description'] : '')), true, false, true) ?>
	<?= $this->tag->tagHtml('meta', array('name'=>'keywords', 'content'=>(!empty($metaTags['keywords']) ? $metaTags['keywords'] : '')), true, false, true) ?>
	<?= $this->tag->tagHtml('meta', array('name'=>'viewport', 'content'=>'width=device-width, initial-scale=1.0'), true, false, true) ?>
	<?= $this->assets->outputCss('cssBefore') ?>
	<?= $this->assets->outputJs('jsBefore') ?>
</head>
<body>
<div class="root">

	<?= $this->getContent() ?>

</div>
<?= $this->assets->outputCss('cssAfter') ?>
<?= $this->assets->outputJs('jsAfter') ?>
</body>
</html>