<div class="top-teaser">
    <div class="content-wrapper">
        <div class="p-wrapper-1-reverse r l appeal">
            <h2>Уникальные авторские работы</h2>
            <p>Продавайте и покупайте напрямую у мастеров</p>
        </div>
    </div>
</div>
<div class="person-teaser">
    <div class="content-wrapper">
        <div class="sections-label">Персона</div>
        <div class="snapshots">
            <div class="fitted"><img src="/files/personsTeaser.jpg" /></div>
        </div>
        <div class="info">
            <div class="thumbs">
                <div class="items">
                    <div class="fitted">
                        <div class="wrapper">
                            <img src="/files/personsTeaser.jpg" />
                        </div>
                    </div>
                </div>
                <div class="items">
                    <div class="fitted">
                        <div class="wrapper">
                            <a href=""><img src="/files/personsTeaser.jpg" /></a>
                        </div>
                    </div>
                </div>
                <div class="items">
                    <div class="fitted">
                        <div class="wrapper">
                            <a href=""><img src="/files/personsTeaser.jpg" /></a>
                        </div>
                    </div>
                </div>
                <div class="items">
                    <div class="fitted">
                        <div class="wrapper">
                            <a href=""><img src="/files/personsTeaser.jpg" /></a>
                        </div>
                    </div>
                </div>
                <div class="items">
                    <div class="fitted">
                        <div class="wrapper">
                            <a href=""><img src="/files/personsTeaser.jpg" /></a>
                        </div>
                    </div>
                </div>
                <div class="items">
                    <div class="fitted">
                        <div class="wrapper">
                            <a href=""><img src="/files/personsTeaser.jpg" /></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="p-wrapper all">
                <div class="user-label table">
                    <div class="tr">
                        <div class="td u-avatar">
                            <a href=""><img src="/files/avatars/1.jpg" /></a>
                        </div>
                        <ul class="td mid u-name">
                            <li><i class="fa fa-star"></i> <a href="">Алиса Селезнёва</a> Москва</li>
                        </ul>
                    </div>
                </div>
                <div class="quotation">
                    <div class="teaser">
                        <p>"Light is radiant energy, usually referring to electromagnetic radiation that is visible to the human eye, and is responsible for the sense of sight."</p>
                    </div>
                    <div class="bold goon"><a href="">Интервью с Алисой Селезнёвой</a> в рубрике "Персона"</div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="content">
    <div class="p-wrapper-1 t content-wrapper">
        <div class="p-wrapper-1-reverse r l clearfix">

        <div class="goods grid">
            <div class="sections-label">Новинки</div>
                <div class="scope">
                    <div class="items">
                        <div class="wrapper clearfix">

                            <div class="fitted">
                                <a href="/marketplace/6"><img src="/files/small/1.jpg" /></a>
                            </div>
                            <div class="info">
                                <div class="name"><i class="overlay"></i><i class="fa fa-bolt"></i> <a href="/marketplace/6">Бусы с мохнатым шариком 5</a></div>
                                <div class="user-label table">
                                    <div class="tr">
                                        <div class="td u-avatar">
                                            <a href=""><img src="/files/avatars/1.jpg" /></a>
                                        </div>
                                        <ul class="td mid u-name">
                                            <li><a href="">Алиса Селезнёва</a> Москва</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="stat clearfix">
                                    <div class="left"><i class="fa fa-thumbs-o-up"></i> 1</div>
                                    <div class="right"><span class="extra-bold price">1500</span> <i class="fa fa-rub"></i></div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="items">
                        <div class="wrapper clearfix">

                            <div class="fitted">
                                <a href="/marketplace/5"><img src="/files/small/1.jpg" /></a>
                            </div>
                            <div class="info">
                                <div class="name"><i class="overlay"></i><i class="fa fa-bolt"></i> <a href="/marketplace/5">Бусы с мохнатым шариком 4</a></div>
                                <div class="user-label table">
                                    <div class="tr">
                                        <div class="td u-avatar">
                                            <a href=""><img src="/files/avatars/1.jpg" /></a>
                                        </div>
                                        <ul class="td mid u-name">
                                            <li><a href="">Алиса Селезнёва</a> Москва</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="stat clearfix">
                                    <div class="left"><i class="fa fa-thumbs-o-up"></i> 1</div>
                                    <div class="right"><span class="extra-bold price">1500</span> <i class="fa fa-rub"></i></div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="items">
                        <div class="wrapper clearfix">

                            <div class="fitted">
                                <a href="/marketplace/4"><img src="/files/small/1.jpg" /></a>
                            </div>
                            <div class="info">
                                <div class="name"><i class="overlay"></i><i class="fa fa-bolt"></i> <a href="/marketplace/4">Бусы с мохнатым шариком 3</a></div>
                                <div class="user-label table">
                                    <div class="tr">
                                        <div class="td u-avatar">
                                            <a href=""><img src="/files/avatars/1.jpg" /></a>
                                        </div>
                                        <ul class="td mid u-name">
                                            <li><a href="">Алиса Селезнёва</a> Москва</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="stat clearfix">
                                    <div class="left"><i class="fa fa-thumbs-o-up"></i> 1</div>
                                    <div class="right"><span class="extra-bold price">1500</span> <i class="fa fa-rub"></i></div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="items">
                        <div class="wrapper clearfix">

                            <div class="fitted">
                                <a href="/marketplace/3"><img src="/files/small/1.jpg" /></a>
                            </div>
                            <div class="info">
                                <div class="name"><i class="overlay"></i><i class="fa fa-bolt"></i> <a href="/marketplace/3">Бусы с мохнатым шариком 2</a></div>
                                <div class="user-label table">
                                    <div class="tr">
                                        <div class="td u-avatar">
                                            <a href=""><img src="/files/avatars/1.jpg" /></a>
                                        </div>
                                        <ul class="td mid u-name">
                                            <li><a href="">Алиса Селезнёва</a> Москва</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="stat clearfix">
                                    <div class="left"><i class="fa fa-thumbs-o-up"></i> 1</div>
                                    <div class="right"><span class="extra-bold price">1500</span> <i class="fa fa-rub"></i></div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="items visible-w1280">
                        <div class="wrapper clearfix">

                            <div class="fitted">
                                <a href="/marketplace/2"><img src="/files/small/1.jpg" /></a>
                            </div>
                            <div class="info">
                                <div class="name"><i class="overlay"></i><i class="fa fa-bolt"></i> <a href="/marketplace/2">Бусы с мохнатым шариком 1</a></div>
                                <div class="user-label table">
                                    <div class="tr">
                                        <div class="td u-avatar">
                                            <a href=""><img src="/files/avatars/1.jpg" /></a>
                                        </div>
                                        <ul class="td mid u-name">
                                            <li><a href="">Алиса Селезнёва</a> Москва</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="stat clearfix">
                                    <div class="left"><i class="fa fa-thumbs-o-up"></i> 1</div>
                                    <div class="right"><span class="extra-bold price">1500</span> <i class="fa fa-rub"></i></div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

            <div class="goods grid">
                <div class="sections-label">Выбор редакции</div>
                <div class="scope">
                    <div class="items">
                        <div class="wrapper clearfix">

                            <div class="fitted">
                                <a href="/marketplace/1"><img src="/files/small/1.jpg" /></a>
                            </div>
                            <div class="info">
                                <div class="name"><i class="overlay"></i><i class="fa fa-bolt"></i> <a href="/marketplace/1">Шляпка Клош из фетра "Дэйзи"</a></div>
                                <div class="user-label table">
                                    <div class="tr">
                                        <div class="td u-avatar">
                                            <a href=""><img src="/files/avatars/1.jpg" /></a>
                                        </div>
                                        <ul class="td mid u-name">
                                            <li><a href="">Алиса Селезнёва</a> Москва</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="stat clearfix">
                                    <div class="left"><i class="fa fa-thumbs-o-up"></i> 1</div>
                                    <div class="right"><span class="extra-bold price">1500</span> <i class="fa fa-rub"></i></div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="items">
                        <div class="wrapper clearfix">

                            <div class="fitted">
                                <a href="/marketplace/2"><img src="/files/small/1.jpg" /></a>
                            </div>
                            <div class="info">
                                <div class="name"><i class="overlay"></i><i class="fa fa-bolt"></i> <a href="/marketplace/2">Бусы с мохнатым шариком 1</a></div>
                                <div class="user-label table">
                                    <div class="tr">
                                        <div class="td u-avatar">
                                            <a href=""><img src="/files/avatars/1.jpg" /></a>
                                        </div>
                                        <ul class="td mid u-name">
                                            <li><a href="">Алиса Селезнёва</a> Москва</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="stat clearfix">
                                    <div class="left"><i class="fa fa-thumbs-o-up"></i> 1</div>
                                    <div class="right"><span class="extra-bold price">1500</span> <i class="fa fa-rub"></i></div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="items">
                        <div class="wrapper clearfix">

                            <div class="fitted">
                                <a href="/marketplace/3"><img src="/files/small/1.jpg" /></a>
                            </div>
                            <div class="info">
                                <div class="name"><i class="overlay"></i><i class="fa fa-bolt"></i> <a href="/marketplace/3">Бусы с мохнатым шариком 2</a></div>
                                <div class="user-label table">
                                    <div class="tr">
                                        <div class="td u-avatar">
                                            <a href=""><img src="/files/avatars/1.jpg" /></a>
                                        </div>
                                        <ul class="td mid u-name">
                                            <li><a href="">Алиса Селезнёва</a> Москва</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="stat clearfix">
                                    <div class="left"><i class="fa fa-thumbs-o-up"></i> 1</div>
                                    <div class="right"><span class="extra-bold price">1500</span> <i class="fa fa-rub"></i></div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="items">
                        <div class="wrapper clearfix">

                            <div class="fitted">
                                <a href="/marketplace/4"><img src="/files/small/1.jpg" /></a>
                            </div>
                            <div class="info">
                                <div class="name"><i class="overlay"></i><i class="fa fa-bolt"></i> <a href="/marketplace/4">Бусы с мохнатым шариком 3</a></div>
                                <div class="user-label table">
                                    <div class="tr">
                                        <div class="td u-avatar">
                                            <a href=""><img src="/files/avatars/1.jpg" /></a>
                                        </div>
                                        <ul class="td mid u-name">
                                            <li><a href="">Алиса Селезнёва</a> Москва</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="stat clearfix">
                                    <div class="left"><i class="fa fa-thumbs-o-up"></i> 1</div>
                                    <div class="right"><span class="extra-bold price">1500</span> <i class="fa fa-rub"></i></div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="items visible-w1280">
                        <div class="wrapper clearfix">

                            <div class="fitted">
                                <a href="/marketplace/5"><img src="/files/small/1.jpg" /></a>
                            </div>
                            <div class="info">
                                <div class="name"><i class="overlay"></i><i class="fa fa-bolt"></i> <a href="/marketplace/5">Бусы с мохнатым шариком 4</a></div>
                                <div class="user-label table">
                                    <div class="tr">
                                        <div class="td u-avatar">
                                            <a href=""><img src="/files/avatars/1.jpg" /></a>
                                        </div>
                                        <ul class="td mid u-name">
                                            <li><a href="">Алиса Селезнёва</a> Москва</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="stat clearfix">
                                    <div class="left"><i class="fa fa-thumbs-o-up"></i> 1</div>
                                    <div class="right"><span class="extra-bold price">1500</span> <i class="fa fa-rub"></i></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>